### ISSUE TITLE
Adapter - where is (msg here) text coming from for CONDITION category?

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/ladder99#10]
As seen in Agent output `NORMAL (msg here)`.

**Comment by bburns** [comment]
That will all be handled here - https://github.com/Ladder99/ladder99/blob/a8134802ca0eda46c7a435762121db489c9f591b/pipeline/adapter/src/cache.js#L100

I removed the '(msg here)' part from the message value last week. Will have to dig more into the condition SHDR handling soon.

**Comment by MRIIOT** [comment]
Can this be closed?

**Comment by bburns** [comment]
closing - conditions will need expanding on but can open another issue for that
