### ISSUE TITLE
Adapter - CCS-PA does not feed Agent on startup from 'query' topic

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/ladder99#11]
I would expect all values from /evt/query to be evaluated and sent to Agent on startup.  For example, printer_start_print_duration remains UNAVAILABLE on startup.

https://github.com/Ladder99/ladder99/blob/d09e81996363005b84758be8a0d9a1ee20678165/models/ccs-pa/inputs.yaml#L91

**Comment by MRIIOT** [comment]
This relates to retained mqtt messages and their ingestion into cache upon adapter startup.

Can this be closed?

**Comment by bburns** [comment]
this works for oxbox - will close
