### ISSUE TITLE
Adapter for Dymo M10 scale

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/ladder99#13]
How to create adapter for scale?

https://github.com/null-none/python-dymo-scale

**Comment by bburns** [comment]
From slack -
https://gist.github.com/PhantomRay/cbccda0d3ab9a9f42d7346cc378d808b

**Comment by bburns** [comment]
Starting on this. A couple more links -

http://steventsnyder.com/reading-a-dymo-usb-scale-using-python/
https://github.com/andyseubert/CoffeeScale

**Comment by bburns** [comment]
Basic driver done - https://github.com/Ladder99/ladder99/blob/main/pipeline/adapter/src/drivers/dymo.js
