### ISSUE TITLE
Does Relay startup block if one Agent is not reachable?

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/ladder99#174]
If setup.yaml calls out multiple Agents, does Relay block on startup if one of the Agents is not reachable?

https://github.com/Ladder99/ladder99/blob/88771563d805d8f95b81895e112dc67de50dcae0/services/relay/src/endpoint.js#L35-L66

**Comment by bburns** [comment]
Good question, but no - this for-loop in the main file just starts each endpoint up and lets them go at their own pace - they run in parallel in js's event loop - 

https://github.com/Ladder99/ladder99/blob/88771563d805d8f95b81895e112dc67de50dcae0/services/relay/src/index.js#L32-L50
