### ISSUE TITLE
l99 example setup - fix mazak machine reference

### ISSUE THREAD

**Issue by bburns** [Ladder99/ladder99#181]
bb: The example setup does watch one device in the mazak agent
ob: Yeah, it is in the config, however, when I open Grafana, it is blank (no machines). Maybe I miss some steps …

**Comment by MRIIOT** [comment]
@bburns where and what is the problem here?

https://github.com/Ladder99/ladder99/blob/fc96345058b35d11d16ce8455404a27c2ac64521/setups/example/setup.yaml#L65

https://github.com/Ladder99/setup-demo/blob/main/setup.yaml

https://github.com/Ladder99/setup-test/blob/main/setup.yaml

**Comment by tukusejssirs** [comment]
Maybe there is no problem at all, maybe there was an issue my config. :thinking: All MTC demo agents from Mazak work as expected now.

**Comment by MRIIOT** [comment]
User issue.

**Comment by bburns** [comment]
That mazak might have been off at the time - I made a note in the docs that can happen -

> The dashboard will show the LIVE status of a Mazak CNC machine, as provided by Mazak (note: the machine may be OFF at certain times of the day) -

**Comment by bburns** [comment]
That mazak might have been off at the time - I added a note in the docs -

> The dashboard will show the LIVE status of a Mazak CNC machine, as provided by Mazak (note: the machine may be OFF at certain times of the day) -
