### ISSUE TITLE
Handle offline mode better in `l99 start` command

### ISSUE THREAD

**Issue by bburns** [Ladder99/ladder99#201]
eg --offline doesn't even work when run with agent - 

```
#3 [internal] load metadata for docker.io/library/ubuntu:22.10
#3 ERROR: failed to do request: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/22.10": dial tcp: lookup registry-1.docker.io on 192.168.65.5:53: no such host
------
 > [internal] load metadata for docker.io/library/ubuntu:22.10:
------
failed to solve: ubuntu:22.10: failed to do request: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/22.10": dial tcp: lookup registry-1.docker.io on 192.168.65.5:53: no such host
```

**Comment by MRIIOT** [comment]
`--offline` should only ensure that Grafana does not pull in plugins and starts up cleanly.  It is assumed that the plugins have been loaded when previously connected to the internet.

Building or pulling images is outside the scope for this task.
User will be required to `docker pull` on an internet connected device, `docker save` on the same device, copy the file to disconnected device, and `docker load` on the disconnected device.

**Comment by MRIIOT** [comment]
`shell/commands/start`

```bash
...
OVERRIDES=OVERRIDES=$SETUP_FOLDER/services/docker-compose.online.yaml
OVERRIDES_OFFLINE=OVERRIDES=$SETUP_FOLDER/services/docker-compose.offline.yaml
...
```

`services/docker-compose.yaml`

```yaml
...
grafana:
  ...
  # GF_INSTALL_PLUGINS:
```

`setups/example/services/docker-compose.online.yaml`

```yaml
...
grafana:
  ...
  GF_INSTALL_PLUGINS: natel-discrete-panel,natel-plotly-panel,michaeldmoore-scatter-panel,dalvany-image-panel
```

`setups/example/services/docker-compose.offline.yaml`

```yaml
...
grafana:
  ...
  # GF_INSTALL_PLUGINS:
```

**Comment by bburns** [comment]
`l99 buildx` builds cross-platform images and pushes them to Docker Hub. It loops over the architectures, building in order, instead of in parallel as before. We can run this on the mriiot linux dev box. 

`l99 start` pulls and runs images with versions as defined in https://github.com/Ladder99/ladder99/blob/main/services/docker-compose.prod.yaml. Currently all at 0.11.0.

Grafana has a Dockerfile that installs the plugins https://github.com/Ladder99/ladder99/blob/main/services/grafana/Dockerfile - `l99 buildx grafana` builds the image and uploads it. 

`l99 ls` lists the images downloaded - 
```
$ l99 ls
Listing ladder99/* images...
REPOSITORY         TAG            IMAGE ID       CREATED       SIZE
ladder99/adapter   0.11.0         6aeb01cc1501   6 days ago    1.06GB
ladder99/agent     2.0.0.13_RC1   219f5df9eee5   5 weeks ago   209MB
ladder99/grafana   0.11.0         e7dd5dd054e9   5 days ago    256MB
ladder99/meter     0.11.0         94c5e7b55464   4 days ago    250MB
ladder99/relay     0.11.0         9df037ea1475   6 days ago    261MB
```

`l99 dev` builds and runs images as defined in the relevant Dockerfiles, eg https://github.com/Ladder99/ladder99/blob/main/services/adapter/Dockerfile. This is used for local development. 

`l99 status` lists running containers - 
```
$ l99 status
project    service     STATUS         IMAGE                              PORTS
ladder99   adapter     Up 5 minutes   ladder99/adapter:0.11.0
ladder99   agent       Up 5 minutes   ladder99/agent:2.0.0.13_RC1        0.0.0.0:5000->5000/tcp
ladder99   dozzle      Up 5 minutes   amir20/dozzle:latest               0.0.0.0:8080->8080/tcp
ladder99   grafana     Up 5 minutes   ladder99/grafana:0.11.0            0.0.0.0:80->3000/tcp
ladder99   meter       Up 5 minutes   ladder99/meter:0.11.0
ladder99   pgadmin     Up 5 minutes   biarms/pgadmin4:4.21               0.0.0.0:5050->5050/tcp
ladder99   portainer   Up 5 minutes   portainer/portainer-ce             8000/tcp, 9443/tcp, 0.0.0.0:9000->9000/tcp
ladder99   postgres    Up 5 minutes   timescale/timescaledb:2.7.0-pg13   127.0.0.1:5432->5432/tcp
ladder99   relay       Up 5 minutes   ladder99/relay:0.11.0
```

If running local dev images, they will show as something like 'ladder99-adapter', with no version.

Also brought buildx and start scripts over to other branch and used them for 0.7.3.

Todo: 
- consolidate/cleanup code in start, dev, compose scripts

**Comment by bburns** [comment]
Consolidated l99 start/dev/compose code.
