### ISSUE TITLE
docs - bring design/*.md into main docs

### ISSUE THREAD

**Issue by bburns** [Ladder99/ladder99#215]
eg https://github.com/Ladder99/ladder99/blob/main/design/design.md

**Comment by MRIIOT** [comment]
I'll be working on this.

**Comment by MRIIOT** [comment]
`ladder99/design` can be removed from GH.

**Comment by bburns** [comment]
where did these notes go?

**Comment by MRIIOT** [comment]
Internal wiki for now.

**Comment by tukusejssirs** [comment]
@bburns, you forget to update `README.md`: now there is a broken link to the screenshot of MTConnect parsing website.

**Comment by bburns** [comment]
@tukusejssirs good catch!
