### ISSUE TITLE
Timezone consistency problem in Postgres ladder 99 functions or raw to public schema

### ISSUE THREAD

**Issue by Dowster64** [Ladder99/ladder99#229]
With ladder 99 running in Docker on a Raspberry pi.  In Australia/Melbourne at 5 past 4pm:
for the session:
```
set timezone = 'Australia/Melbourne'
select now()
```
2023-12-07 16:05:54.69165+11  correct

`select time, value from get_last_value('Main/1000'|| '/Availability', '1w');`
for the time, returns:

2023-12-08 03:05:05.798+11 ( incorrect - it's added 11 hrs on to a UTC time as a local time, so that's now a future time - see the day is 8 not 7) 

Setting session tz to UTC:
`select now()`
2023-12-07 05:11:39.885238+00 correct, we are +11 hrs at the moment

`select time, value from get_last_value('Main/1000'|| '/Availability', '1w');`
for the time, returns:
2023-12-07 16:05:05.798+00 (note this is a UTC tz but with a local time, hence a future time as above)

The time field is type timestamp with timezone.   

Pi has it's clock  configured as follows:

```
pi@fiabtest:/etc $ timedatectl
               Local time: Thu 2023-12-07 15:59:25 AEDT
           Universal time: Thu 2023-12-07 04:59:25 UTC
                 RTC time: n/a
                Time zone: Australia/Melbourne (AEDT, +1100)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
pi@fiabtest:/etc $
```

Thanks,

**Comment by Dowster64** [comment]
Well, I did use a function that returned the latest value, but I've since truncated the history table and still have wrong data. not sure what I have to purge...

**Comment by ottobolyos** [comment]
Thanks for reporting this issue, @Dowster64! :pray:

I need to look into it a bit more deeper, maybe I could find some time tomorrow. I am quite sure though that it has to be fixed somewhere (probably in the `meter` app).

**Comment by Dowster64** [comment]
@ottobolyos , I am using an inventcom CNCnetPDM adapter and, after re-installing ladder99 (and finding out about tags!) I discovered that everything was fine with your defaults, the time going off when I used their adapter.  Long story short, the CNCnetPDM adapter is the culprit!  It is sending / publishing local time as Zulu time, hence the doubling up.  It was 20:50+11 (my time with timezone) not 20:50+00 (ie UTC 11 hours ahead).  Many apologies.  

`2023-12-07T20:50:52.490Z|1000:COMP_QTY|316|1000:AX1|812.189 851.344 530.992 105.991 |1000:AX2|394.635 267.098 121.891 335.673 |1000:STATN|2|1000:STATT|Producing|1000:MODEN|1|1000:MODET|Memory|1000:PRGCU|2|1000:PRGMN|4712|1000:SEQCU|1|1000:FEEDR|748|1000:SPSPD|536|1000:ALMST|0|1000:TOOL1|5|1000:TOOL2|5|1000:ALMNR|0|1000:ALMTX|No `
