### ISSUE TITLE
l99 shell script bad substitution

### ISSUE THREAD

**Issue by robot-ranger** [Ladder99/ladder99#233]
the command `l99 init tester` resulted in 

```
line 46: ${$L99_HOME:-$repo_root}: bad substituion
line 69: /home/[myuser]/shell/commands/init: No such file or directory
```

I noted that the path in the trace from line 69 is missing `/ladder99` repo folder. 
"/home/[myuser]/shell/commands/init" does, in fact, not exist.

"/home/[myuser]***/ladder99***/shell/commands/init" does exist

I ran `echo $L99_HOME` and it returned `/home/[myuser]/ladder99`

**Comment by ottobolyos** [comment]
I fixed this issue in PR #234. Could you test the PR if it fixes this issue at your end please? Thanks in advance! :pray:

**Comment by robot-ranger** [comment]
ill test this week

**Comment by robot-ranger** [comment]
works! im just learning l99, but `l99 init` worked fine, created a new setup in setups folder.

super quick response! thx 🙏
