### ISSUE TITLE
pgAdmin cannot connect to db

### ISSUE THREAD

**Issue by robot-ranger** [Ladder99/ladder99#235]
im trying to use pgadmin, but i cant seem to connect to the db.

i can see the docker service running:

```
CONTAINER ID   IMAGE                                    COMMAND                  CREATED             STATUS             PORTS                                                           NAMES
f7cd0e3bea64   timescale/timescaledb:2.7.0-pg13         "docker-entrypoint.s…"   About an hour ago   Up About an hour   127.0.0.1:5432->5432/tcp                                        postgres
```

but i cant seem to connect from the pgadmin dashboard at [my_ip]:5050. I also cannot connect from dBeaver on a windows machine.

there is data in grafana, so i assume the db is working....

Should the ports for postgres container show `127.0.0.1`? from my experience, i have better luck using `0.0.0.0` to expose ports in docker containers, but i will admit i dont know enough about container networking to know why or if that is just a symptomatic treatment as opposed to the root cause

ETA: i am getting connection refused; so im thinking this is a networking issue

**Comment by ottobolyos** [comment]
`127.0.0.1` here means you can access it locally (on the server) only. You should use `postgres` hostname, as both `pgadmin` and `postgres`/`db` containers are in the same network. This is Docker thing and you could change it in the Docker Compose file.

**Comment by robot-ranger** [comment]
ty ty. works w/ `postgres` as hostname

it was one of those feelings where i knew my knowledge was not complete.

**Comment by ottobolyos** [comment]
I suggest reading the docs, in this case [this](https://docs.docker.com/network/).

**Comment by robot-ranger** [comment]
> I suggest reading the docs, in this case [this](https://docs.docker.com/network/).

I appreciate that - but in this case, ladder99 has black-boxed a little bit of this. the `docker-compose.yml` is VERY thin and its not readily apparent where all of the services are getting their configs from

**Comment by ottobolyos** [comment]
Indeed. There three Docker Compose files basically and two config files.
- [`services/docker-compose.yaml`](https://github.com/Ladder99/ladder99/blob/main/services/docker-compose.yaml) is the main compose file;
- [`services/docker-compose.prod.yaml`](https://github.com/Ladder99/ladder99/blob/main/services/docker-compose.prod.yaml) overrides some stuff in the main compose file when run in `production` profile;
- [`setups/example/services/docker-compose.yaml`](https://github.com/Ladder99/ladder99/blob/main/setups/example/services/docker-compose.yaml) overrides some stuff based based on the user requirements (you are supposed to edit this file);
- [`setups/example/setup.yaml`](https://github.com/Ladder99/ladder99/blob/main/setups/example/setup.yaml) contains half of the config;
- [`setups/example/.env-example`](https://github.com/Ladder99/ladder99/blob/main/setups/example/.env-exmple) copied to `.env` in that folder and modified by the user, contains the other half of the config.
