### ISSUE TITLE
RTD do not seem to update from main branch.

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/ladder99#236]
Updated: https://github.com/Ladder99/ladder99/blob/main/docs/page/drivers/fanuc/installation-docker.md

Not Updated:  https://docs.ladder99.com/en/latest/page/drivers/fanuc/installation-docker.html

**Comment by ottobolyos** [comment]
Fixed by f8e493d55c45ad4dac37ff85cfb694039ea1ab43, closing.
