### ISSUE TITLE
EVENT MESSAGE not populating model

### ISSUE THREAD

**Issue by MRIIOT** [Ladder99/ladder99#9]
MTC EVENT MESSAGE does not parse into MTC Agent model.

`TCP sending string 2021-07-09T13:11:53.428Z|ccs-dev_msg|13: printer service req ...`

`2021-07-09T13:38:35.443169Z | Message |   |   | ccs-dev_msg | 46 | UNAVAILABLE`

Is this related to Agent ShdrVerion?

```
ShdrVersion - Specifies the SHDR protocol version used by the adapter. When greater than one (1), allows multiple complex observations, like Condition and Message on the same line. If it equials one (1), then any observation requiring more than a key/value pair need to be on separate lines. This is the default for all adapters.

Default: 1
```

I can't figure out why the Agent doesn't output SHDR in debug log.  I thought this was a feature before.

```
logger_config
{
    logging_level = debug
    output = cout
}
```

**Comment by bburns** [comment]
Oh, messages require an additional field. From https://github.com/mtconnect/cppagent#adapter-agent-protocol-version-17 - 

> The next special format is the Message. There is one additional field, native_code, which needs to be included: 2014-09-29T23:59:33.460470Z|message|CHG_INSRT|Change Inserts

For now I just did like so - in future we can try the DATA_SET representation - 

```
  - key: dev_msg
    category: EVENT
    type: MESSAGE
    value: "Object.entries(<status-faults>).map(([id, fault]) => fault.description).join(', ')"
    nativeCode: NativeCode
```

---------

Agent shows eg

    <Message dataItemId="pa1-dev_msg" nativeCode="NativeCode" sequence="138" timestamp="2021-08-06T09:25:45.538Z">hard fault 1</Message>

---------

For Agent debugging, the trace level includes the shdr inputs - https://github.com/mtconnect/cppagent#logger_config-configuration-items

```
logger_config {
   logging_level = trace
}
```

> agent        | 583479 TRACE [3] input.connector: (Port:53511) Received line: '2021-08-06T09:25:04.370Z|pa2-feed_message|NativeCode|printer service required, take up motor timeout, low ribbon'


----------

I used `ag` to help debug it (like grep but colors matches) - 

    sh/start ccs-pa adapter broker play agent | ag message
